name: AWS Audits

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 11 * * *"  # Runs daily at noon UK time

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install boto3
          python3 -m pip show boto3  # Verify boto3 installation

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

  iam-audit:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run IAM audit
        run: |
          /opt/hostedtoolcache/Python/3.12.4/x64/bin/python3 aws-audits/iam_audit.py  # Use the full path to Python

  s3-audit:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run S3 audit
        run: |
          /opt/hostedtoolcache/Python/3.12.4/x64/bin/python3 aws-audits/s3_audit.py  # Use the full path to Python

  sg-audit:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Security Group audit across all regions
        run: |
          /opt/hostedtoolcache/Python/3.12.4/x64/bin/python3 aws-audits/sg_audit.py  # Use the full path to Python
